name: SonarQube Analysis
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  sonar-analysis:
    uses: ArquisoftV-Microservice-Project/devops-workflows/.github/workflows/sonar.yml@main
    secrets: inherit